<template>
  <div>
    <a-drawer
      :title="props.mode === 'edit' ? '编辑文章' : '发布文章'"
      :open="open"
      :width="width < 768 ? '100%' : '768px'"
      :footer-style="{ textAlign: 'right' }"
      @close="open = false"
    >
      <a-form
        ref="postFormRef"
        :model="postForm"
        :rules="rules"
        layout="vertical"
      >
        <a-row :gutter="16">
          <a-col :span="12">
            <a-form-item label="标题" name="title">
              <a-input
                v-model:value="postForm.title"
                placeholder="请输入标题"
                :maxlength="50"
              />
            </a-form-item>
          </a-col>
          <a-col :span="12">
            <a-form-item label="作者" name="author">
              <a-input v-model:value="postForm.author" placeholder="作者昵称" />
            </a-form-item>
          </a-col>
        </a-row>

        <a-row :gutter="16">
          <a-col :span="12">
            <a-form-item label="别名" name="alias">
              <a-input
                v-model:value="postForm.alias"
                placeholder="请输入别名"
              />
            </a-form-item>
          </a-col>
        </a-row>
        <a-row :gutter="16">
          <a-col :span="12">
            <a-form-item label="分类" name="category_id">
              <a-select
                v-model:value="postForm.category_id"
                placeholder="请选择分类"
              >
                <a-select-option
                  v-for="c in categories"
                  :key="c.id"
                  :value="c.id"
                >
                  {{ c.name }}
                </a-select-option>
              </a-select>
            </a-form-item>
          </a-col>
          <a-col :span="12">
            <a-form-item label="标签" name="tags_id">
              <a-select
                mode="multiple"
                v-model:value="postForm.tags_id"
                :max-tag-count="2"
                placeholder="请选择或搜索标签"
                :loading="tagsLoading"
                show-search
                :filter-option="false"
                @search="handleTagsSearch"
                @popup-scroll="handleTagsPopupScroll"
              >
                <template #maxTagPlaceholder="omittedValues">
                  <span style="color: red"
                    >+ {{ omittedValues.length }} ...</span
                  >
                </template>
                <a-select-option v-for="t in tags" :key="t.id" :value="t.id">
                  {{ t.name }}
                </a-select-option>
                <a-select-option v-if="tagsLoading" disabled key="loading">
                  <a-spin size="small" /> 加载中...
                </a-select-option>
                <a-select-option v-else-if="tagsHasMore" disabled key="more">
                  <span class="text-gray-400">滚动加载更多</span>
                </a-select-option>
                <a-select-option v-else disabled key="end">
                  <span class="text-gray-400">已加载全部</span>
                </a-select-option>
              </a-select>
            </a-form-item>
          </a-col>
        </a-row>

        <a-form-item label="封面" name="thumbnail">
          <div class="flex items-center gap-3">
            <span class="text-sm text-gray-600 whitespace-nowrap"
              >图片链接：</span
            >
            <a-input
              v-model:value="postForm.thumbnail"
              placeholder="输入图片链接或从相册选择"
              style="flex: 1"
            />
            <a-button
              type="link"
              size="small"
              @click="thumbnailModalOpen = true"
            >
              <template #icon>
                <Icon icon="solar:gallery-bold-duotone" />
              </template>
              从相册选择
            </a-button>
          </div>
        </a-form-item>

        <a-form-item label="描述" name="description">
          <a-textarea
            v-model:value="postForm.description"
            placeholder="请输入描述"
            :rows="4"
          />
          <span class="float-right">
            <a-button type="link" size="small" @click="autoGenerateDescription">
              自动截取
            </a-button>
            <a-button
              type="link"
              size="small"
              @click="postForm.description = ''"
            >
              清空
            </a-button>
          </span>
        </a-form-item>

        <a-form-item label="内容" name="content">
          <a-textarea
            v-model:value="postForm.content"
            placeholder="请输入内容"
            :rows="6"
          />
        </a-form-item>

        <a-form-item label="发布时间" name="created_at">
          <a-date-picker show-time v-model:value="createdAt" />
        </a-form-item>

        <div class="flex items-center gap-2 my-4">
          <span>发布</span>
          <a-switch v-model:checked="postForm.is_publish" />
          <a-divider type="vertical" />
          <span>置顶</span>
          <a-switch v-model:checked="postForm.is_top" />
        </div>
      </a-form>

      <template #extra>
        <a-space>
          <a-button type="primary" @click="submitForm"> 发布 </a-button>
          <a-button @click="open = false">取消</a-button>
        </a-space>
      </template>
    </a-drawer>

    <!-- 封面选择弹窗 -->
    <PhotoSelect
      v-model:open="thumbnailModalOpen"
      @selected-picture="handleSelectPicture"
    />
  </div>
</template>

<script lang="ts" setup>
import { useRouter } from "vue-router";
import { message, type FormInstance } from "ant-design-vue";

import { useVModel, useWindowSize, useDebounceFn } from "@vueuse/core";
import dayjs from "dayjs";

import PhotoSelect from "@/components/PhotoSelect/index.vue";
import { queryAllByTypeAPI, queryLabelListAPI } from "@/api/label";
import { createPostAPI, updatePostAPI } from "@/api/post";

import type { PostReq } from "@/types/post";
import type { LabelVO } from "@/types/label";
import { Icon } from "@iconify/vue";

const props = defineProps<{
  mode: "create" | "edit";
  open: boolean;
  postForm: PostReq;
}>();

const emit = defineEmits<{
  (e: "update:open", value: boolean): void;
  (e: "update:postForm", value: PostReq): void;
}>();

// Router
const router = useRouter();

// 响应式表单对象
const postFormRef = ref<FormInstance>();
const postForm = useVModel(props, "postForm", emit);
const open = useVModel(props, "open", emit);

// 时间字段处理
const createdAt = computed({
  get: () => dayjs(postForm.value.created_at),
  set: val => (postForm.value.created_at = val.toISOString()),
});

const tagsIDValidator = (_rule: any, value: any) => {
  if (value.length > 2) {
    return Promise.reject(new Error("最多选择2个标签"));
  }
  return Promise.resolve();
};

// 校验规则
const rules = {
  title: [{ required: true, message: "请输入标题" }],
  content: [{ required: true, message: "请输入内容" }],
  author: [{ required: true, message: "请输入作者" }],
  alias: [{ required: true, message: "请输入别名" }],
  tags_id: [{ validator: tagsIDValidator }],
};

// 分类 / 标签
const categories = ref<LabelVO[]>([]);
const tags = ref<LabelVO[]>([]);
const tagsLoading = ref(false);
const tagsHasMore = ref(true);
const tagsPage = ref(1);
const tagsPageSize = 20;
const tagsKeyword = ref("");

// 获取数据
const fetchCategories = async () => {
  const res = await queryAllByTypeAPI("category");
  categories.value = res.data;
};
const fetchTags = async (reset = false) => {
  if (tagsLoading.value) return;
  if (!reset && !tagsHasMore.value) return;

  if (reset) {
    tagsPage.value = 1;
    tagsHasMore.value = true;
    tags.value = [];
  }

  tagsLoading.value = true;
  try {
    const res = await queryLabelListAPI({
      page_no: tagsPage.value,
      page_size: tagsPageSize,
      label_type: "tag",
      keyword: tagsKeyword.value || undefined,
    });
    const newTags = res.data.list || [];
    tags.value = reset ? newTags : [...tags.value, ...newTags];
    tagsHasMore.value = newTags.length === tagsPageSize;
    tagsPage.value++;
  } finally {
    tagsLoading.value = false;
  }
};

const handleTagsSearch = useDebounceFn((value: string) => {
  tagsKeyword.value = value;
  fetchTags(true);
}, 300);

const handleTagsPopupScroll = (e: Event) => {
  const target = e.target as HTMLElement;
  if (target.scrollTop + target.offsetHeight >= target.scrollHeight - 10) {
    fetchTags();
  }
};

// 自动生成描述
const autoGenerateDescription = () => {
  postForm.value.description = postForm.value.content
    .replace(/[\n\t]/g, " ")
    .replace(/<[^>]*>/g, "")
    .replace(/&(nbsp|amp|quot|apos);/g, "")
    .slice(0, 150)
    .trim();
};

const clearForm = () => {
  postForm.value = {
    created_at: new Date().toISOString(),
    title: "",
    content: "",
    description: "",
    author: "",
    alias: "",
    category_id: "",
    tags_id: [],
    is_publish: true,
    is_top: false,
    thumbnail: "",
  };
};

// 提交处理
const submitForm = () => {
  postFormRef.value?.validate().then(async () => {
    if (props.mode === "create") {
      await createPostAPI(postForm.value);
      message.success("发布成功");
    } else {
      await updatePostAPI(postForm.value);
      message.success("编辑成功");
    }
    // 清空表单
    clearForm();
    open.value = false;
    router.push({ name: "PostList" });
  });
};

// 封面选择
const thumbnailModalOpen = ref(false);

const handleSelectPicture = (picture: string) => {
  postForm.value.thumbnail = picture;
};

// 屏幕尺寸
const { width } = useWindowSize();

// 初始化
onMounted(() => {
  fetchCategories();
  fetchTags(true);
});

onActivated(() => {
  fetchCategories();
  fetchTags(true);
});
</script>

<style lang="scss">
.full-modal {
  .ant-modal {
    max-width: 100%;
    top: 0;
    margin: 0;
    padding-bottom: 0;
  }
  .ant-modal-content {
    display: flex;
    flex-direction: column;
    height: 100vh;
  }
  .ant-modal-body {
    flex: 1;
    overflow-y: auto;
  }
}

::-webkit-scrollbar {
  width: 8px;
}
</style>
